# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ded5ccfe8fccbe6a5e20754e675c51fac9babc25a12803d6098058af8f2ae46e44af5eb27a31f5215554bfcc0a7b39458464f395c8e2582d848970e2e1a476c2

test:
  secret_key_base: 3480aba6610cef5e3c909d4b3b1bc116b91293d0b882c62df4ed06d0e15d084748145bdc5b4f296d20613c347a77f744ea82db4f0924a47cd89f86c901b97608

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
